// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracity.ApiClients.DataPlatform.DataApi
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Tags.
    /// </summary>
    public static partial class TagsExtensions
    {
            /// <summary>
            /// Retrieve metadata tags in Veracity.
            /// </summary>
            /// <remarks>
            /// Default returns approved and non deleted tags.
            /// Use Query parameters to includes non approved and deleted (needs to be
            /// DataAdmin to perform this action)
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='includeDeleted'>
            /// </param>
            /// <param name='includeNonVeracityApproved'>
            /// </param>
            public static IList<Tag> GetTags(this ITags operations, bool? includeDeleted = default(bool?), bool? includeNonVeracityApproved = default(bool?))
            {
                return operations.GetTagsAsync(includeDeleted, includeNonVeracityApproved).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Retrieve metadata tags in Veracity.
            /// </summary>
            /// <remarks>
            /// Default returns approved and non deleted tags.
            /// Use Query parameters to includes non approved and deleted (needs to be
            /// DataAdmin to perform this action)
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='includeDeleted'>
            /// </param>
            /// <param name='includeNonVeracityApproved'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Tag>> GetTagsAsync(this ITags operations, bool? includeDeleted = default(bool?), bool? includeNonVeracityApproved = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetTagsWithHttpMessagesAsync(includeDeleted, includeNonVeracityApproved, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Inserts tags and returns the inserted new inserted tags with ID's
            /// &lt;remarks&gt;
            /// Id is not required for the input
            /// &lt;/remarks&gt;
            /// </summary>
            /// <remarks>
            /// Inserts tags and returns the inserted new inserted tags with ID's
            /// &lt;remarks&gt;
            /// Id is not required for the input
            /// &lt;/remarks&gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static IList<Tag> InsertTags(this ITags operations, IList<Tag> body = default(IList<Tag>))
            {
                return operations.InsertTagsAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Inserts tags and returns the inserted new inserted tags with ID's
            /// &lt;remarks&gt;
            /// Id is not required for the input
            /// &lt;/remarks&gt;
            /// </summary>
            /// <remarks>
            /// Inserts tags and returns the inserted new inserted tags with ID's
            /// &lt;remarks&gt;
            /// Id is not required for the input
            /// &lt;/remarks&gt;
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Tag>> InsertTagsAsync(this ITags operations, IList<Tag> body = default(IList<Tag>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.InsertTagsWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
