// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Interfaces
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// CreateUserSse operations.
    /// </summary>
    public partial interface ICreateUserSse
    {
        /// <summary>
        /// Create a user. Request with server sent
        /// events&lt;br/&gt;Restricted, only to be used by Veracity Platform
        /// and select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> CreateUserWithHttpMessagesAsync(string tenantId, CreateUserPayload body = default, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a user. Request with server sent
        /// events&lt;br/&gt;Restricted, only to be used by Veracity Platform
        /// and select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task CreateUserAsync(string tenantId, CreateUserPayload body = default, string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Create multiple users. Request with server sent
        /// events&lt;br/&gt;Restricted, only to be used by Veracity Platform
        /// and select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> CreateUsersWithHttpMessagesAsync(string tenantId, CreateUsersPayload body = default, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Create multiple users. Request with server sent
        /// events&lt;br/&gt;Restricted, only to be used by Veracity Platform
        /// and select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='body'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task CreateUsersAsync(string tenantId, CreateUsersPayload body = default, string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// &lt;br/&gt;Restricted, only to be used by Veracity Platform and
        /// select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='email'>
        /// The email address of the user
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<UserExistanceTypes?>> ResolveUserWithHttpMessagesAsync(string tenantId, string email, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// &lt;br/&gt;Restricted, only to be used by Veracity Platform and
        /// select partners
        /// </summary>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='email'>
        /// The email address of the user
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<UserExistanceTypes?> ResolveUserAsync(string tenantId, string email, string requestId = default, CancellationToken cancellationToken = default);

    }
}
