// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Interfaces
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// DomainEventsHelper operations.
    /// </summary>
    public partial interface IDomainEventsHelper
    {
        /// <summary>
        /// Resolve the route ids to be used in the label header of the
        /// messages based on a list of service principals&lt;br/&gt;
        /// </summary>
        /// <param name='body'>
        /// </param>
        /// <param name='formating'>
        /// Possible values include: 'Unformatted', 'DomainLabelFormatted'
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<RouteDetails>> ResolveDomainEventRoutesWithHttpMessagesAsync(IEnumerable<string> body = default, string formating = default, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Resolve the route ids to be used in the label header of the
        /// messages based on a list of service principals&lt;br/&gt;
        /// </summary>
        /// <param name='body'>
        /// </param>
        /// <param name='formating'>
        /// Possible values include: 'Unformatted', 'DomainLabelFormatted'
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<RouteDetails> ResolveDomainEventRoutesAsync(IEnumerable<string> body = default, string formating = default, string requestId = default, CancellationToken cancellationToken = default);

    }
}
