// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracity.ApiClients.MyServices.MyServicesV3Api
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// To access the service use
    /// https://api.veracity.com/Veracity/Services/V3. Access to
    /// https://myapiv3.dnvgl.com will be blocked January 2020.
    ///
    /// The Service API provides a consistent interface for accessing data
    /// about the user, as well as the Veracity platform in general. At its
    /// core is a REST service built up of "view - points" where you can read,
    /// write and update information. Authentication is handled through Azure
    /// B2C OAuth 2.
    ///
    ///
    /// Build version: 2022.03.25.4.
    ///
    /// Veracity is designed to help companies unlock, qualify, combine and
    /// prepare data for analytics and benchmarking. Veracity will give you
    /// access to industrial applications and data analytics services that can
    /// help you make better use of your data to optimize your operations. Here
    /// you can combine your own data with other data sets available for
    /// purchase or subscription, to create new insights or solutions.
    ///
    /// __Note__ that the Discover endpoints are moving to Directory. For this
    /// release they are hidden from the swagger document, but Discover will be
    /// removed completely at a later stage.
    /// </summary>
    public partial interface IMyServicesV3ApiClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICompaniesDirectory.
        /// </summary>
        ICompaniesDirectory CompaniesDirectory { get; }

        /// <summary>
        /// Gets the IDataContainerService.
        /// </summary>
        IDataContainerService DataContainerService { get; }

        /// <summary>
        /// Gets the IMy.
        /// </summary>
        IMy My { get; }

        /// <summary>
        /// Gets the IOptions.
        /// </summary>
        IOptions Options { get; }

        /// <summary>
        /// Gets the IServicesDirectory.
        /// </summary>
        IServicesDirectory ServicesDirectory { get; }

        /// <summary>
        /// Gets the IStatusService.
        /// </summary>
        IStatusService StatusService { get; }

        /// <summary>
        /// Gets the IThisModel.
        /// </summary>
        IThisModel ThisModel { get; }

        /// <summary>
        /// Gets the IUsersDirectory.
        /// </summary>
        IUsersDirectory UsersDirectory { get; }

    }
}
