// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    /// <summary>
    /// Represents a create response for tenant information.
    /// </summary>
    public partial class CreateTenantResponse
    {
        /// <summary>
        /// Initializes a new instance of the CreateTenantResponse class.
        /// </summary>
        public CreateTenantResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateTenantResponse class.
        /// </summary>
        /// <param name="tenantId">The ID of the tenant.</param>
        /// <param name="users">The users that are part of the tenant.</param>
        /// <param name="applications">The applications that are part of the
        /// tenant.</param>
        /// <param name="properties">The extension properties of the tenant
        /// entity. extension properties are case sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.</param>
        /// <param name="domains">list of email domains that is associated with
        /// the tenant. Only available for tenants with the tenant type
        /// veracity_default</param>
        /// <param name="legalEntityName">The name of the legal entity, should
        /// be the same as the name of the tenant. And is synced with the legal
        /// entity in MDM.</param>
        /// <param name="tenantType">Possible values include:
        /// 'veracity_hidden', 'veracity_private', 'veracity_default'</param>
        /// <param name="dnvCustomerId">The global customer id from MDM and
        /// salesforce</param>
        /// <param name="legalEntityId">The internal MDM id for the legal
        /// entity</param>
        public CreateTenantResponse(System.Guid? tenantId = default, IEnumerable<UsersResponse> users = default, IEnumerable<ApplicationResponse> applications = default, IEnumerable<ExtensionProperty> properties = default, IEnumerable<string> domains = default, string legalEntityName = default, TenantTypes? tenantType = default, string dnvCustomerId = default, string legalEntityId = default)
        {
            TenantId = tenantId;
            Users = users;
            Applications = applications;
            Properties = properties;
            Domains = domains;
            LegalEntityName = legalEntityName;
            TenantType = tenantType;
            DnvCustomerId = dnvCustomerId;
            LegalEntityId = legalEntityId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ID of the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public System.Guid? TenantId { get; set; }

        /// <summary>
        /// Gets or sets the users that are part of the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public IEnumerable<UsersResponse> Users { get; set; }

        /// <summary>
        /// Gets or sets the applications that are part of the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "applications")]
        public IEnumerable<ApplicationResponse> Applications { get; set; }

        /// <summary>
        /// Gets or sets the extension properties of the tenant entity.
        /// extension properties are case sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IEnumerable<ExtensionProperty> Properties { get; set; }

        /// <summary>
        /// Gets or sets list of email domains that is associated with the
        /// tenant. Only available for tenants with the tenant type
        /// veracity_default
        /// </summary>
        [JsonProperty(PropertyName = "domains")]
        public IEnumerable<string> Domains { get; set; }

        /// <summary>
        /// Gets or sets the name of the legal entity, should be the same as
        /// the name of the tenant. And is synced with the legal entity in MDM.
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityName")]
        public string LegalEntityName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'veracity_hidden',
        /// 'veracity_private', 'veracity_default'
        /// </summary>
        [JsonProperty(PropertyName = "tenantType")]
        public TenantTypes? TenantType { get; set; }

        /// <summary>
        /// Gets or sets the global customer id from MDM and salesforce
        /// </summary>
        [JsonProperty(PropertyName = "dnvCustomerId")]
        public string DnvCustomerId { get; set; }

        /// <summary>
        /// Gets or sets the internal MDM id for the legal entity
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityId")]
        public string LegalEntityId { get; set; }

    }
}
