// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class CreateTenantPayload
    {
        /// <summary>
        /// Initializes a new instance of the CreateTenantPayload class.
        /// </summary>
        public CreateTenantPayload()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateTenantPayload class.
        /// </summary>
        /// <param name="admins">List of the initial administrators for the
        /// tenant</param>
        /// <param name="applications">the list of applications that should be
        /// installed in the tenant</param>
        /// <param name="properties">Extension properties for the
        /// tenant.</param>
        /// <param name="domains">list of email domains that is associated with
        /// the tenant. Only available for tenants with the tenant type
        /// veracity_default</param>
        /// <param name="controlOptions">Possible values include:
        /// 'StopOnFailure', 'TryUndo', 'Continue'</param>
        /// <param name="legalEntityName">The name of the legal entity, should
        /// be the same as the name of the tenant. And is synced with the legal
        /// entity (site) in MDM.</param>
        /// <param name="tenantType">Possible values include:
        /// 'veracity_hidden', 'veracity_private', 'veracity_default'</param>
        /// <param name="dnvCustomerId">The global customer id from MDM and
        /// salesforce</param>
        /// <param name="legalEntityId">The internal MDM id for the legal
        /// entity</param>
        public CreateTenantPayload(IEnumerable<Administrator> admins = default, IEnumerable<Application> applications = default, IEnumerable<ExtensionProperty> properties = default, IEnumerable<string> domains = default, ControlOptionTypes? controlOptions = default, string legalEntityName = default, TenantTypes? tenantType = default, string dnvCustomerId = default, string legalEntityId = default)
        {
            Admins = admins;
            Applications = applications;
            Properties = properties;
            Domains = domains;
            ControlOptions = controlOptions;
            LegalEntityName = legalEntityName;
            TenantType = tenantType;
            DnvCustomerId = dnvCustomerId;
            LegalEntityId = legalEntityId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of the initial administrators for the tenant
        /// </summary>
        [JsonProperty(PropertyName = "admins")]
        public IEnumerable<Administrator> Admins { get; set; }

        /// <summary>
        /// Gets or sets the list of applications that should be installed in
        /// the tenant
        /// </summary>
        [JsonProperty(PropertyName = "applications")]
        public IEnumerable<Application> Applications { get; set; }

        /// <summary>
        /// Gets or sets extension properties for the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IEnumerable<ExtensionProperty> Properties { get; set; }

        /// <summary>
        /// Gets or sets list of email domains that is associated with the
        /// tenant. Only available for tenants with the tenant type
        /// veracity_default
        /// </summary>
        [JsonProperty(PropertyName = "domains")]
        public IEnumerable<string> Domains { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'StopOnFailure', 'TryUndo',
        /// 'Continue'
        /// </summary>
        [JsonProperty(PropertyName = "controlOptions")]
        public ControlOptionTypes? ControlOptions { get; set; }

        /// <summary>
        /// Gets or sets the name of the legal entity, should be the same as
        /// the name of the tenant. And is synced with the legal entity (site)
        /// in MDM.
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityName")]
        public string LegalEntityName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'veracity_hidden',
        /// 'veracity_private', 'veracity_default'
        /// </summary>
        [JsonProperty(PropertyName = "tenantType")]
        public TenantTypes? TenantType { get; set; }

        /// <summary>
        /// Gets or sets the global customer id from MDM and salesforce
        /// </summary>
        [JsonProperty(PropertyName = "dnvCustomerId")]
        public string DnvCustomerId { get; set; }

        /// <summary>
        /// Gets or sets the internal MDM id for the legal entity
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityId")]
        public string LegalEntityId { get; set; }

    }
}
