// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class ElementRightSlim
    {
        /// <summary>
        /// Initializes a new instance of the ElementRightSlim class.
        /// </summary>
        public ElementRightSlim()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ElementRightSlim class.
        /// </summary>
        public ElementRightSlim(string elementId = default, System.Guid? applicationId = default, string accessLevel = default, IEnumerable<ExtensionProperty> properties = default)
        {
            ElementId = elementId;
            ApplicationId = applicationId;
            AccessLevel = accessLevel;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elementId")]
        public string ElementId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public System.Guid? ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accessLevel")]
        public string AccessLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IEnumerable<ExtensionProperty> Properties { get; set; }

    }
}
