// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class InstallApplicationsResponse
    {
        /// <summary>
        /// Initializes a new instance of the InstallApplicationsResponse
        /// class.
        /// </summary>
        public InstallApplicationsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InstallApplicationsResponse
        /// class.
        /// </summary>
        /// <param name="applications">The applications that where
        /// installed</param>
        public InstallApplicationsResponse(IEnumerable<ApplicationResponse> applications = default)
        {
            Applications = applications;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the applications that where installed
        /// </summary>
        [JsonProperty(PropertyName = "applications")]
        public IEnumerable<ApplicationResponse> Applications { get; set; }

    }
}
