// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.InternalPlatformApiV4.Models
{
    using Newtonsoft.Json;
    public partial class UsersResponse
    {
        /// <summary>
        /// Initializes a new instance of the UsersResponse class.
        /// </summary>
        public UsersResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UsersResponse class.
        /// </summary>
        /// <param name="profileId">the users profile id,</param>
        /// <param name="tenantId">the tenant id of the userProfile</param>
        /// <param name="isServicePrincipal">indicates if the user is a service
        /// principal</param>
        /// <param name="isLimitedUser">Indicates it the user is a limited user
        /// (vessel user)</param>
        /// <param name="name">Optional: The display name of the user.</param>
        /// <param name="userId">The userId from id.veracity.com, cannot be
        /// specified if Email is set</param>
        /// <param name="email">The email address of the user, cannot be
        /// specified if UserId is set</param>
        /// <param name="isAdmin">Annotates if the user should be added as an
        /// admin user or not, if not specified the user will be added as a
        /// normal user</param>
        public UsersResponse(System.Guid? profileId = default, string tenantId = default, bool? isServicePrincipal = default, bool? isLimitedUser = default, string name = default, System.Guid? userId = default, string email = default, bool? isAdmin = default)
        {
            ProfileId = profileId;
            TenantId = tenantId;
            IsServicePrincipal = isServicePrincipal;
            IsLimitedUser = isLimitedUser;
            Name = name;
            UserId = userId;
            Email = email;
            IsAdmin = isAdmin;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the users profile id,
        /// </summary>
        [JsonProperty(PropertyName = "profileId")]
        public System.Guid? ProfileId { get; set; }

        /// <summary>
        /// Gets or sets the tenant id of the userProfile
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or sets indicates if the user is a service principal
        /// </summary>
        [JsonProperty(PropertyName = "isServicePrincipal")]
        public bool? IsServicePrincipal { get; set; }

        /// <summary>
        /// Gets or sets indicates it the user is a limited user (vessel user)
        /// </summary>
        [JsonProperty(PropertyName = "isLimitedUser")]
        public bool? IsLimitedUser { get; set; }

        /// <summary>
        /// Gets or sets optional: The display name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the userId from id.veracity.com, cannot be specified
        /// if Email is set
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid? UserId { get; set; }

        /// <summary>
        /// Gets or sets the email address of the user, cannot be specified if
        /// UserId is set
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets annotates if the user should be added as an admin user
        /// or not, if not specified the user will be added as a normal user
        /// </summary>
        [JsonProperty(PropertyName = "isAdmin")]
        public bool? IsAdmin { get; set; }

    }
}
