// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.ServicesApiV3.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class ValidationError
    {
        /// <summary>
        /// Initializes a new instance of the ValidationError class.
        /// </summary>
        public ValidationError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ValidationError class.
        /// </summary>
        public ValidationError(int subCode, string url = default, IEnumerable<string> violatedPolicies = default, bool? subscriptionMissing = default, string message = default, string information = default, string supportCode = default)
        {
            Url = url;
            ViolatedPolicies = violatedPolicies;
            SubscriptionMissing = subscriptionMissing;
            Message = message;
            Information = information;
            SubCode = subCode;
            SupportCode = supportCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "violatedPolicies")]
        public IEnumerable<string> ViolatedPolicies { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionMissing")]
        public bool? SubscriptionMissing { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "information")]
        public string Information { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subCode")]
        public int SubCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supportCode")]
        public string SupportCode { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
