// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MinimalSchemaReferenceDto
    {
        /// <summary>
        /// Initializes a new instance of the MinimalSchemaReferenceDto class.
        /// </summary>
        public MinimalSchemaReferenceDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MinimalSchemaReferenceDto class.
        /// </summary>
        public MinimalSchemaReferenceDto(System.Guid? id = default, string shortName = default, int? version = default)
        {
            Id = id;
            ShortName = shortName;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

    }
}
