// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class SchemaRowValidatorDefinitionDto
    {
        /// <summary>
        /// Initializes a new instance of the SchemaRowValidatorDefinitionDto
        /// class.
        /// </summary>
        public SchemaRowValidatorDefinitionDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SchemaRowValidatorDefinitionDto
        /// class.
        /// </summary>
        /// <param name="logicalOperator">Possible values include: 'And',
        /// 'Or'</param>
        /// <param name="rowValidatorType">Possible values include:
        /// 'RequiredIfNotNull', 'RequiredIfRegexMatch',
        /// 'RequiredIfSumExceedsThreshold'</param>
        public SchemaRowValidatorDefinitionDto(string name = default, string checkParameter = default, IEnumerable<string> columnsToCheck = default, IEnumerable<string> columnsToAffect = default, LogicalOperator? logicalOperator = default, RowValidatorType? rowValidatorType = default, string message = default)
        {
            Name = name;
            CheckParameter = checkParameter;
            ColumnsToCheck = columnsToCheck;
            ColumnsToAffect = columnsToAffect;
            LogicalOperator = logicalOperator;
            RowValidatorType = rowValidatorType;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "checkParameter")]
        public string CheckParameter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnsToCheck")]
        public IEnumerable<string> ColumnsToCheck { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnsToAffect")]
        public IEnumerable<string> ColumnsToAffect { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'And', 'Or'
        /// </summary>
        [JsonProperty(PropertyName = "logicalOperator")]
        public LogicalOperator? LogicalOperator { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'RequiredIfNotNull',
        /// 'RequiredIfRegexMatch', 'RequiredIfSumExceedsThreshold'
        /// </summary>
        [JsonProperty(PropertyName = "rowValidatorType")]
        public RowValidatorType? RowValidatorType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
