// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WorkspaceUserWriteDTO
    {
        /// <summary>
        /// Initializes a new instance of the WorkspaceUserWriteDTO class.
        /// </summary>
        public WorkspaceUserWriteDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WorkspaceUserWriteDTO class.
        /// </summary>
        /// <param name="role">Possible values include: 'Admin', 'Contributor',
        /// 'Reader'</param>
        public WorkspaceUserWriteDTO(System.Guid? userId = default(System.Guid?), Role? role = default(Role?))
        {
            UserId = userId;
            Role = role;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid? UserId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Admin', 'Contributor',
        /// 'Reader'
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public Role? Role { get; set; }

    }
}
