// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ResourceMetadata
    {
        /// <summary>
        /// Initializes a new instance of the ResourceMetadata class.
        /// </summary>
        public ResourceMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceMetadata class.
        /// </summary>
        public ResourceMetadata(string title = default, string description = default, Icon icon = default, IEnumerable<Tag> tags = default)
        {
            Title = title;
            Description = description;
            Icon = icon;
            Tags = tags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "icon")]
        public Icon Icon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IEnumerable<Tag> Tags { get; set; }

    }
}
