// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.DataPlatform.DataApi.Models
{
    using Newtonsoft.Json;
    public partial class ResourceDistributedUser
    {
        /// <summary>
        /// Initializes a new instance of the ResourceDistributedUser class.
        /// </summary>
        public ResourceDistributedUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceDistributedUser class.
        /// </summary>
        public ResourceDistributedUser(System.Guid? userId = default)
        {
            UserId = userId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid? UserId { get; set; }

    }
}
