// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracity.ApiClients.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SchemaReadDTO
    {
        /// <summary>
        /// Initializes a new instance of the SchemaReadDTO class.
        /// </summary>
        public SchemaReadDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SchemaReadDTO class.
        /// </summary>
        public SchemaReadDTO(System.Guid? schemaId = default(System.Guid?), string name = default(string), string shortName = default(string), string description = default(string), bool? isPredefined = default(bool?), System.Guid? industryId = default(System.Guid?), System.Guid? workspaceId = default(System.Guid?))
        {
            SchemaId = schemaId;
            Name = name;
            ShortName = shortName;
            Description = description;
            IsPredefined = isPredefined;
            IndustryId = industryId;
            WorkspaceId = workspaceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaId")]
        public System.Guid? SchemaId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPredefined")]
        public bool? IsPredefined { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "industryId")]
        public System.Guid? IndustryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workspaceId")]
        public System.Guid? WorkspaceId { get; set; }

    }
}
