// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veracity.ApiClients.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SchemaColumnReadDTO
    {
        /// <summary>
        /// Initializes a new instance of the SchemaColumnReadDTO class.
        /// </summary>
        public SchemaColumnReadDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SchemaColumnReadDTO class.
        /// </summary>
        /// <param name="schemaColumnType">Possible values include:
        /// 'Validation', 'Metadata'</param>
        /// <param name="metaType">Possible values include: 'NotApplicable',
        /// 'FileName', 'UploadTime', 'RowCorrection'</param>
        public SchemaColumnReadDTO(int? schemaColumnId = default(int?), string name = default(string), System.Guid? schemaVersionId = default(System.Guid?), bool? mustBePresent = default(bool?), int? columnOrder = default(int?), string metaFormat = default(string), IList<ColumnValidatorColumnReadDTO> columnValidators = default(IList<ColumnValidatorColumnReadDTO>), SchemaColumnType? schemaColumnType = default(SchemaColumnType?), MetaType? metaType = default(MetaType?))
        {
            SchemaColumnId = schemaColumnId;
            Name = name;
            SchemaVersionId = schemaVersionId;
            MustBePresent = mustBePresent;
            ColumnOrder = columnOrder;
            MetaFormat = metaFormat;
            ColumnValidators = columnValidators;
            SchemaColumnType = schemaColumnType;
            MetaType = metaType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaColumnId")]
        public int? SchemaColumnId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaVersionId")]
        public System.Guid? SchemaVersionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mustBePresent")]
        public bool? MustBePresent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnOrder")]
        public int? ColumnOrder { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metaFormat")]
        public string MetaFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnValidators")]
        public IList<ColumnValidatorColumnReadDTO> ColumnValidators { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Validation', 'Metadata'
        /// </summary>
        [JsonProperty(PropertyName = "schemaColumnType")]
        public SchemaColumnType? SchemaColumnType { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'NotApplicable', 'FileName',
        /// 'UploadTime', 'RowCorrection'
        /// </summary>
        [JsonProperty(PropertyName = "metaType")]
        public MetaType? MetaType { get; set; }

    }
}
