// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ColumnValidatorColumnWriteDTO
    {
        /// <summary>
        /// Initializes a new instance of the ColumnValidatorColumnWriteDTO
        /// class.
        /// </summary>
        public ColumnValidatorColumnWriteDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ColumnValidatorColumnWriteDTO
        /// class.
        /// </summary>
        /// <param name="severity">Possible values include: 'Error', 'Warning',
        /// 'Correction'</param>
        public ColumnValidatorColumnWriteDTO(int? columnValidatorId = default, Severity? severity = default)
        {
            ColumnValidatorId = columnValidatorId;
            Severity = severity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "columnValidatorId")]
        public int? ColumnValidatorId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Error', 'Warning',
        /// 'Correction'
        /// </summary>
        [JsonProperty(PropertyName = "severity")]
        public Severity? Severity { get; set; }

    }
}
