// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Schemas166.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Schemas166
    {
        [EnumMember(Value = "Length")]
        Length,
        [EnumMember(Value = "Range")]
        Range,
        [EnumMember(Value = "Regex")]
        Regex,
        [EnumMember(Value = "Required")]
        Required,
        [EnumMember(Value = "Type")]
        Type
    }
    internal static class Schemas166EnumExtension
    {
        internal static string ToSerializedValue(this Schemas166? value)
        {
            return value == null ? null : ((Schemas166)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Schemas166 value)
        {
            switch( value )
            {
                case Schemas166.Length:
                    return "Length";
                case Schemas166.Range:
                    return "Range";
                case Schemas166.Regex:
                    return "Regex";
                case Schemas166.Required:
                    return "Required";
                case Schemas166.Type:
                    return "Type";
            }
            return null;
        }

        internal static Schemas166? ParseSchemas166(this string value)
        {
            switch( value )
            {
                case "Length":
                    return Schemas166.Length;
                case "Range":
                    return Schemas166.Range;
                case "Regex":
                    return Schemas166.Regex;
                case "Required":
                    return Schemas166.Required;
                case "Type":
                    return Schemas166.Type;
            }
            return null;
        }
    }
}
