// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi.Interfaces;

namespace DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Container.
    /// </summary>
    public static partial class ContainerExtensions
    {
            /// <summary>
            /// Get a list of container sets
            /// </summary>
            /// <remarks>
            /// Default behavior: Name expanded
            /// Other fields are optionally expandable.
            /// To serve the front-end, they will also need an option to provide/expand:
            /// - the name/shortname of the schema that the schema version belongs to
            /// - the id of the schema the version belongs to
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            public static IEnumerable<ContainerSetReadDTO> GetContainerList(this IContainer operations, string id)
            {
                return operations.GetContainerListAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a list of container sets
            /// </summary>
            /// <remarks>
            /// Default behavior: Name expanded
            /// Other fields are optionally expandable.
            /// To serve the front-end, they will also need an option to provide/expand:
            /// - the name/shortname of the schema that the schema version belongs to
            /// - the id of the schema the version belongs to
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IEnumerable<ContainerSetReadDTO>> GetContainerListAsync(this IContainer operations, string id, CancellationToken cancellationToken = default)
            {
                using (var _result = await operations.GetContainerListWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new container
            /// </summary>
            /// <remarks>
            /// Required user input is:
            /// - Container Name
            /// - Processing region instance
            /// - Schema ID
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid. workspace Id
            /// </param>
            /// <param name='body'>
            /// </param>
            public static ContainerSetReadDTO AddContainer(this IContainer operations, string id, ContainerSetWriteDTO body = default)
            {
                return operations.AddContainerAsync(id, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new container
            /// </summary>
            /// <remarks>
            /// Required user input is:
            /// - Container Name
            /// - Processing region instance
            /// - Schema ID
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid. workspace Id
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ContainerSetReadDTO> AddContainerAsync(this IContainer operations, string id, ContainerSetWriteDTO body = default, CancellationToken cancellationToken = default)
            {
                using (var _result = await operations.AddContainerWithHttpMessagesAsync(id, body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets container details
            /// </summary>
            /// <remarks>
            /// Gets container details
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            /// <param name='containerId'>
            /// Format - uuid.
            /// </param>
            public static ContainerSetReadDTO GetContainer(this IContainer operations, string id, string containerId)
            {
                return operations.GetContainerAsync(id, containerId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets container details
            /// </summary>
            /// <remarks>
            /// Gets container details
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid.
            /// </param>
            /// <param name='containerId'>
            /// Format - uuid.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ContainerSetReadDTO> GetContainerAsync(this IContainer operations, string id, string containerId, CancellationToken cancellationToken = default)
            {
                using (var _result = await operations.GetContainerWithHttpMessagesAsync(id, containerId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Removes a container
            /// </summary>
            /// <remarks>
            /// Removes a container
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid. workspace Id
            /// </param>
            /// <param name='containerId'>
            /// Format - uuid.
            /// </param>
            public static void Remove(this IContainer operations, string id, string containerId)
            {
                operations.RemoveAsync(id, containerId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Removes a container
            /// </summary>
            /// <remarks>
            /// Removes a container
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Format - uuid. workspace Id
            /// </param>
            /// <param name='containerId'>
            /// Format - uuid.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task RemoveAsync(this IContainer operations, string id, string containerId, CancellationToken cancellationToken = default)
            {
                (await operations.RemoveWithHttpMessagesAsync(id, containerId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
