// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.AzureDevOps.GitApi.Models
{
    using Newtonsoft.Json;
    /// <summary>
    /// Represents the metadata information for the entities.
    /// </summary>
    public partial class VeracityCoreApiV4ResponsesMetadata
    {
        /// <summary>
        /// Initializes a new instance of the
        /// VeracityCoreApiV4ResponsesMetadata class.
        /// </summary>
        public VeracityCoreApiV4ResponsesMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// VeracityCoreApiV4ResponsesMetadata class.
        /// </summary>
        /// <param name="type">The entity type.</param>
        /// <param name="createdBy">The creator.</param>
        /// <param name="createDate">The creation date.</param>
        /// <param name="modifiedBy">The modifier.</param>
        /// <param name="modifiedDate">The modification date.</param>
        public VeracityCoreApiV4ResponsesMetadata(string type = default, string createdBy = default, System.DateTime? createDate = default, string modifiedBy = default, System.DateTime? modifiedDate = default)
        {
            Type = type;
            CreatedBy = createdBy;
            CreateDate = createDate;
            ModifiedBy = modifiedBy;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the entity type.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

        /// <summary>
        /// Gets the creator.
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; private set; }

        /// <summary>
        /// Gets the creation date.
        /// </summary>
        [JsonProperty(PropertyName = "createDate")]
        public System.DateTime? CreateDate { get; private set; }

        /// <summary>
        /// Gets the modifier.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public string ModifiedBy { get; private set; }

        /// <summary>
        /// Gets the modification date.
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; private set; }

    }
}
