// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.AzureDevOps.GitApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class VeracityCoreApiV4ResponsesTenantResponseEx
    {
        /// <summary>
        /// Initializes a new instance of the
        /// VeracityCoreApiV4ResponsesTenantResponseEx class.
        /// </summary>
        public VeracityCoreApiV4ResponsesTenantResponseEx()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// VeracityCoreApiV4ResponsesTenantResponseEx class.
        /// </summary>
        /// <param name="userId">The user id of the user that used in the query
        /// for the tenant</param>
        /// <param name="isAdmin">Indicates if the user that is used in the
        /// query is an admin of the tenant</param>
        /// <param name="legalEntityName">The legal entity name.</param>
        /// <param name="dnvCustomerId">The DNV customer ID.</param>
        /// <param name="legalEntityId">The legal entity ID.</param>
        /// <param name="tenantType">The tenant type.</param>
        /// <param name="logoUri">The logo URI.</param>
        /// <param name="groupsIsActivated">Value indicating if group is
        /// activated</param>
        /// <param name="name">The name of the tenant entity.</param>
        /// <param name="tenantId">The ID of the tenant.</param>
        /// <param name="properties">The extension properties of the tenant
        /// entity. extension properties are case sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.</param>
        /// <param name="accessHubTenantHomeUrl">get the url to the tenants
        /// home page in access hub</param>
        public VeracityCoreApiV4ResponsesTenantResponseEx(System.Guid? userId = default, bool? isAdmin = default, string legalEntityName = default, string dnvCustomerId = default, string legalEntityId = default, string tenantType = default, string logoUri = default, bool? groupsIsActivated = default, string name = default, System.Guid? tenantId = default, VeracityCoreApiV4ResponsesMetadata metadata = default, IEnumerable<VeracityCoreApiV4ResponsesExtensionProperty> properties = default, string accessHubTenantHomeUrl = default)
        {
            UserId = userId;
            IsAdmin = isAdmin;
            LegalEntityName = legalEntityName;
            DnvCustomerId = dnvCustomerId;
            LegalEntityId = legalEntityId;
            TenantType = tenantType;
            LogoUri = logoUri;
            GroupsIsActivated = groupsIsActivated;
            Name = name;
            TenantId = tenantId;
            Metadata = metadata;
            Properties = properties;
            AccessHubTenantHomeUrl = accessHubTenantHomeUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the user id of the user that used in the query for the
        /// tenant
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid? UserId { get; set; }

        /// <summary>
        /// Gets or sets indicates if the user that is used in the query is an
        /// admin of the tenant
        /// </summary>
        [JsonProperty(PropertyName = "isAdmin")]
        public bool? IsAdmin { get; set; }

        /// <summary>
        /// Gets or sets the legal entity name.
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityName")]
        public string LegalEntityName { get; set; }

        /// <summary>
        /// Gets or sets the DNV customer ID.
        /// </summary>
        [JsonProperty(PropertyName = "dnvCustomerId")]
        public string DnvCustomerId { get; set; }

        /// <summary>
        /// Gets or sets the legal entity ID.
        /// </summary>
        [JsonProperty(PropertyName = "legalEntityId")]
        public string LegalEntityId { get; set; }

        /// <summary>
        /// Gets or sets the tenant type.
        /// </summary>
        [JsonProperty(PropertyName = "tenantType")]
        public string TenantType { get; set; }

        /// <summary>
        /// Gets or sets the logo URI.
        /// </summary>
        [JsonProperty(PropertyName = "logoUri")]
        public string LogoUri { get; set; }

        /// <summary>
        /// Gets or sets value indicating if group is activated
        /// </summary>
        [JsonProperty(PropertyName = "groupsIsActivated")]
        public bool? GroupsIsActivated { get; set; }

        /// <summary>
        /// Gets or sets the name of the tenant entity.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the ID of the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public System.Guid? TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public VeracityCoreApiV4ResponsesMetadata Metadata { get; set; }

        /// <summary>
        /// Gets or sets the extension properties of the tenant entity.
        /// extension properties are case sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IEnumerable<VeracityCoreApiV4ResponsesExtensionProperty> Properties { get; set; }

        /// <summary>
        /// Gets or sets get the url to the tenants home page in access hub
        /// </summary>
        [JsonProperty(PropertyName = "accessHubTenantHomeUrl")]
        public string AccessHubTenantHomeUrl { get; set; }

    }
}
