// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.PlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    /// <summary>
    /// Represents a response for an application license.
    /// </summary>
    public partial class ApplicationLicenseResponse
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationLicenseResponse class.
        /// </summary>
        public ApplicationLicenseResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationLicenseResponse class.
        /// </summary>
        /// <param name="accessLevel">The access level of the license. Only
        /// applicable for application that has access levels defined in
        /// developer.veracity.com.</param>
        /// <param name="applicationUrl">The url to the application page in
        /// including tenant id if not system tenant</param>
        /// <param name="name">The name of the application.</param>
        /// <param name="applicationId">The ID of the application. This is the
        /// same as the serviceId in developer.</param>
        /// <param name="applicationInstanceId">The globally unique identifier
        /// (GUID) for the application.</param>
        /// <param name="accessHubApplicationUrl">The url to the application
        /// page in access hub.</param>
        /// <param name="tenantId">The ID of the tenant.</param>
        /// <param name="properties">The extension properties of the tenant
        /// entity. extension properties are case-sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.</param>
        /// <param name="accessHubTenantHomeUrl">get the url to the tenants
        /// home page in access hub</param>
        /// <param name="systemTags">Gets or sets the list of system generated
        /// tags associated with the tenant entity.</param>
        /// <param name="tags">Gets or sets the list of tags associated with
        /// the tenant entity.</param>
        public ApplicationLicenseResponse(string accessLevel = default, string applicationUrl = default, string name = default, System.Guid? applicationId = default, System.Guid? applicationInstanceId = default, string accessHubApplicationUrl = default, System.Guid? tenantId = default, Metadata metadata = default, IEnumerable<ExtensionProperty> properties = default, string accessHubTenantHomeUrl = default, IEnumerable<string> systemTags = default, IEnumerable<string> tags = default)
        {
            AccessLevel = accessLevel;
            ApplicationUrl = applicationUrl;
            Name = name;
            ApplicationId = applicationId;
            ApplicationInstanceId = applicationInstanceId;
            AccessHubApplicationUrl = accessHubApplicationUrl;
            TenantId = tenantId;
            Metadata = metadata;
            Properties = properties;
            AccessHubTenantHomeUrl = accessHubTenantHomeUrl;
            SystemTags = systemTags;
            Tags = tags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the access level of the license. Only applicable for
        /// application that has access levels defined in
        /// developer.veracity.com.
        /// </summary>
        [JsonProperty(PropertyName = "accessLevel")]
        public string AccessLevel { get; set; }

        /// <summary>
        /// Gets or sets the url to the application page in including tenant id
        /// if not system tenant
        /// </summary>
        [JsonProperty(PropertyName = "applicationUrl")]
        public string ApplicationUrl { get; set; }

        /// <summary>
        /// Gets or sets the name of the application.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the ID of the application. This is the same as the
        /// serviceId in developer.
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public System.Guid? ApplicationId { get; set; }

        /// <summary>
        /// Gets or sets the globally unique identifier (GUID) for the
        /// application.
        /// </summary>
        [JsonProperty(PropertyName = "applicationInstanceId")]
        public System.Guid? ApplicationInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the url to the application page in access hub.
        /// </summary>
        [JsonProperty(PropertyName = "accessHubApplicationUrl")]
        public string AccessHubApplicationUrl { get; set; }

        /// <summary>
        /// Gets or sets the ID of the tenant.
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public System.Guid? TenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public Metadata Metadata { get; set; }

        /// <summary>
        /// Gets or sets the extension properties of the tenant entity.
        /// extension properties are case-sensitive and shall user
        /// {appPrefix}_{propertyName} format, appPrefixes are defined in
        /// developer.veracity.com.
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IEnumerable<ExtensionProperty> Properties { get; set; }

        /// <summary>
        /// Gets or sets get the url to the tenants home page in access hub
        /// </summary>
        [JsonProperty(PropertyName = "accessHubTenantHomeUrl")]
        public string AccessHubTenantHomeUrl { get; set; }

        /// <summary>
        /// Gets or sets the list of system generated tags associated with the
        /// tenant entity.
        /// </summary>
        [JsonProperty(PropertyName = "systemTags")]
        public IEnumerable<string> SystemTags { get; set; }

        /// <summary>
        /// Gets or sets the list of tags associated with the tenant entity.
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IEnumerable<string> Tags { get; set; }

    }
}
