// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.PlatformApiV4.Models
{
    using Newtonsoft.Json;
    public partial class IsMemberResponse
    {
        /// <summary>
        /// Initializes a new instance of the IsMemberResponse class.
        /// </summary>
        public IsMemberResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IsMemberResponse class.
        /// </summary>
        public IsMemberResponse(System.Guid? userId = default, string email = default, string name = default, bool? isDirect = default, System.Guid? througGroupId = default)
        {
            UserId = userId;
            Email = email;
            Name = name;
            IsDirect = isDirect;
            ThrougGroupId = througGroupId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public System.Guid? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDirect")]
        public bool? IsDirect { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "througGroupId")]
        public System.Guid? ThrougGroupId { get; set; }

    }
}
