// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Linq;

namespace DNV.ApiClients.Veracity.Identity.PlatformApiV4.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    public partial class PolicyErrorResponse
    {
        /// <summary>
        /// Initializes a new instance of the PolicyErrorResponse class.
        /// </summary>
        public PolicyErrorResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PolicyErrorResponse class.
        /// </summary>
        /// <param name="correlationId">This is the correlation id for the
        /// request, it can be used to track the request in the logs. You can
        /// control the value by setting the request-id header in the
        /// request</param>
        /// <param name="supportCode">this will be deprecated in the future,
        /// use CorrelationId instead</param>
        /// <param name="subCode">an additional code that can be used to
        /// identify the error, pass this code to the support team when
        /// reporting the error</param>
        /// <param name="message">A human readable message that describes the
        /// error</param>
        /// <param name="information">Additional information about the
        /// error</param>
        public PolicyErrorResponse(string url = default, IEnumerable<string> violatedPolicies = default, bool? subscriptionMissing = default, string correlationId = default, string supportCode = default, int? subCode = default, string message = default, string information = default)
        {
            Url = url;
            ViolatedPolicies = violatedPolicies;
            SubscriptionMissing = subscriptionMissing;
            CorrelationId = correlationId;
            SupportCode = supportCode;
            SubCode = subCode;
            Message = message;
            Information = information;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "violatedPolicies")]
        public IEnumerable<string> ViolatedPolicies { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionMissing")]
        public bool? SubscriptionMissing { get; private set; }

        /// <summary>
        /// Gets this is the correlation id for the request, it can be used to
        /// track the request in the logs. You can control the value by setting
        /// the request-id header in the request
        /// </summary>
        [JsonProperty(PropertyName = "correlationId")]
        public string CorrelationId { get; private set; }

        /// <summary>
        /// Gets this will be deprecated in the future, use CorrelationId
        /// instead
        /// </summary>
        [JsonProperty(PropertyName = "supportCode")]
        public string SupportCode { get; private set; }

        /// <summary>
        /// Gets an additional code that can be used to identify the error,
        /// pass this code to the support team when reporting the error
        /// </summary>
        [JsonProperty(PropertyName = "subCode")]
        public int? SubCode { get; private set; }

        /// <summary>
        /// Gets a human readable message that describes the error
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// Gets additional information about the error
        /// </summary>
        [JsonProperty(PropertyName = "information")]
        public string Information { get; private set; }

    }
}
