// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.Identity.PlatformApiV4.Interfaces
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Me operations.
    /// </summary>
    public partial interface IMe
    {
        /// <summary>
        /// Get the user info for the logged in user
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get details for the logged on user&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<GlobalUserDetailsResponse>> GetMyInfoWithHttpMessagesAsync(string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the user info for the logged in user
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get details for the logged on user&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<GlobalUserDetailsResponse> GetMyInfoAsync(string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the applications the user has a license for
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all applications the user has access to&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<IEnumerable<ApplicationLicenseResponse>>> GetMyApplicationsWithHttpMessagesAsync(string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the applications the user has a license for
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all applications the user has access to&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IEnumerable<ApplicationLicenseResponse>> GetMyApplicationsAsync(string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all applications the user has a license for in a given tenant
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all applications in a tenant the user has access to&lt;br/&gt;
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<IEnumerable<ApplicationLicenseResponse>>> GetMyTenantApplicationsWithHttpMessagesAsync(string tenantId, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all applications the user has a license for in a given tenant
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all applications in a tenant the user has access to&lt;br/&gt;
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IEnumerable<ApplicationLicenseResponse>> GetMyTenantApplicationsAsync(string tenantId, string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the users group memberships
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get the groups the logged on user belongs to&lt;br/&gt;
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<IEnumerable<GroupResponse>>> GetMyGroupsWithHttpMessagesAsync(string tenantId, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get the users group memberships
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get the groups the logged on user belongs to&lt;br/&gt;
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id (or dnvCustomerId for veracity_default tenants)
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IEnumerable<GroupResponse>> GetMyGroupsAsync(string tenantId, string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all tenants the user is a member of
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all tenants the logged on user is a member of&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<IEnumerable<TenantResponseEx>>> GetMyTenantsWithHttpMessagesAsync(string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get all tenants the user is a member of
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all tenants the logged on user is a member of&lt;br/&gt;
        /// </remarks>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IEnumerable<TenantResponseEx>> GetMyTenantsAsync(string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get tenants with the application installed and the user has a
        /// license
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all tenants the logged on user is a member of and has access to
        /// the application&lt;br/&gt;
        /// </remarks>
        /// <param name='applicationId'>
        /// The applicationId is the same as serviceId in developer
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<IEnumerable<TenantResponse>>> GetMyTenantsWithApplicationWithHttpMessagesAsync(System.Guid applicationId, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get tenants with the application installed and the user has a
        /// license
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Get all tenants the logged on user is a member of and has access to
        /// the application&lt;br/&gt;
        /// </remarks>
        /// <param name='applicationId'>
        /// The applicationId is the same as serviceId in developer
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IEnumerable<TenantResponse>> GetMyTenantsWithApplicationAsync(System.Guid applicationId, string requestId = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Important process, verifies that the authenticated user has
        /// accepted all required Veracity policies for the given application.
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Verify Veracity user policies, returns an empty 202 response if all
        /// policies are ok, 406 with an error response that contains the url
        /// to send the user to correct the policy issue&lt;br/&gt;
        /// </remarks>
        /// <param name='applicationId'>
        /// The applicationId is the same as serviceId in developer
        /// </param>
        /// <param name='returnUrl'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        Task<HttpOperationResponse> VerifyUserPolicyWithHttpMessagesAsync(System.Guid applicationId, string returnUrl = default, string requestId = default, Dictionary<string, IList<string>> customHeaders = null, CancellationToken cancellationToken = default);

        /// <summary>
        /// Important process, verifies that the authenticated user has
        /// accepted all required Veracity policies for the given application.
        ///
        ///
        /// </summary>
        /// <remarks>
        /// Verify Veracity user policies, returns an empty 202 response if all
        /// policies are ok, 406 with an error response that contains the url
        /// to send the user to correct the policy issue&lt;br/&gt;
        /// </remarks>
        /// <param name='applicationId'>
        /// The applicationId is the same as serviceId in developer
        /// </param>
        /// <param name='returnUrl'>
        /// </param>
        /// <param name='requestId'>
        /// A correlation token to use when looking in the logs.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task VerifyUserPolicyAsync(System.Guid applicationId, string returnUrl = default, string requestId = default, CancellationToken cancellationToken = default);

    }
}
