// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DNV.ApiClients.Veracity.DataPlatform.DataApi
{
    using AutoRest.ApiClients;
    using AutoRest.ApiClients.Common;
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IDataApiClient : AutoRest.ApiClients.Common.IApiClient, System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IAccess.
        /// </summary>
        IAccess Access { get; }

        /// <summary>
        /// Gets the IApplicationOperations.
        /// </summary>
        IApplicationOperations Application { get; }

        /// <summary>
        /// Gets the IDataStewards.
        /// </summary>
        IDataStewards DataStewards { get; }

        /// <summary>
        /// Gets the IKeyTemplates.
        /// </summary>
        IKeyTemplates KeyTemplates { get; }

        /// <summary>
        /// Gets the ILedger.
        /// </summary>
        ILedger Ledger { get; }

        /// <summary>
        /// Gets the IResources.
        /// </summary>
        IResources Resources { get; }

        /// <summary>
        /// Gets the ITags.
        /// </summary>
        ITags Tags { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

        /// <summary>
        /// Gets the IGroups.
        /// </summary>
        IGroups Groups { get; }

    }
}
