env:
  RELEASE: false
  YML_OUTPUT: nuget-output
on:
  workflow_call:
    inputs:
      input-file:
        required: true
        type: string
      api-name:
        required: true
        type: string
      csharp:
        type: boolean
      typescript:
        type: boolean
      python:
        type: boolean
      output-folder:
        type: string
      client-name:
        type: string
      namespace:
        type: string

jobs:
  autorest_generate:
    name: Autorest Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install AutoRest
        continue-on-error: true
        run: |
          npm i -g autorest
          autorest --version:3.5 --legacy

      - name: Generate Code
        run: |          
          cp ./.github/workflows/autorest/*.md $HOME/.autorest/@autorest_core@3.5.1/node_modules/@autorest/core/dist/resources/
          rm  ${{ inputs.output-folder }}/*.cs
          rm  ${{ inputs.output-folder }}/Models/*.cs
          wget ${{ inputs.input-file }} -O swagger.json

          autorest \
            --input-file:swagger.json \
            --output-folder:"${{ inputs.output-folder }}" \
            --override-client-name:"${{ inputs.client-name }}" \
            --namespace:"${{ inputs.namespace }}" \
            --csharp:${{ inputs.csharp }} \
            --typescript:${{ inputs.typescript }} \
            --python:${{ inputs.python }} \
            --use:@cuteribs/autorest.csharp@latest \
            --use:@cuteribs/autorest.python@latest \
            --use:@cuteribs/autorest.typescript@latest \
            --legacy \
            --v3 \
            --version:3.5

          git config user.email "actions-bot@users.noreply.github.com"
          git config user.name "github actions bot"
          git commit -m "Update generated code" || echo "No change to commit"
    
          echo "::debug::Push commit to remote"
          git push