env:
  RELEASE: false
  YML_OUTPUT: nuget-output
on:
    workflow_call:
      inputs:
        input-file:
          required: true
          type: string
        api-name:
          required: true
          type: string
          
jobs:
    autorest_generate:
      name: Autorest Generate
      runs-on: windows-latest  
      steps:
        - uses: actions/checkout@v3
    
        - name: Download latest swagger.json
          run: |
            $INPUT_FILE="${{ inputs.input-file }}"
            $API_NAME="${{ inputs.api-name }}"

            cd assets
            Invoke-WebRequest "$INPUT_FILE" -O "$API_NAME.swagger.json"

            if (Test-Path ../src/$API_NAME) {
              rm ../src/$API_NAME/*.cs

              if (Test-Path ../src/$API_NAME/Models) {
                rm ../src/$API_NAME/Models/*.cs
              }
            }

            npm i -g autorest
            autorest "$API_NAME.autorest.yml" --version:3.5 --use:@cuteribs/autorest.csharp@2.3.0-2

            git config user.email "actions-bot@users.noreply.github.com"
            git config user.name "github actions bot"
            git commit -a -m "Update generated code" || echo "No change to commit"
    
            echo "::debug::Push commit to remote"
            git push
