env:
  RELEASE: false
  YML_OUTPUT: nuget-output
on:
    workflow_call:
      inputs:
        input-file:
          required: true
          type: string
        api-name:
          required: true
          type: string
          
jobs:
    autorest_generate:
      name: Autorest Generate
      runs-on: ubuntu-latest
      env:
        INPUT_FILE: ${{ inputs.input-file }}
        API_NAME: ${{ inputs.api-name }}
  
      steps:
        - uses: actions/checkout@v3
    
        - name: Download latest swagger.json
          run: |
            cd assets
            wget $INPUT_FILE -O $API_NAME.swagger.json

            rm ../src/$API_NAME/*.cs
            rm ../src/$API_NAME/Models/*.cs

            npm i -g autorest
            autorest $API_NAME.autorest.yml --version:3.5 