name: DNV.ApiClients.Veracity.DataPlatform.DataWorkbenchApiV2

on:
  workflow_dispatch:
    inputs:
      require_publish:
        type: boolean
        default: false
  push:
    branches:
    - main
    paths:
    - 'src/DataWorkbenchApiV2/**'
    - '.github/workflows/DataWorkbenchApiV2.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/DataWorkbenchApiV2/**'
    - '.github/workflows/DataWorkbenchApiV2.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      config-file: assets/DataWorkbenchApiV2.md
      project-name: DNV.ApiClients.Veracity.DataPlatform.DataWorkbenchApiV2.ApiClient
      output-folder: src/DNV.ApiClients.Veracity.DataPlatform.DataWorkbenchApiV2
  nuget-publish:
    needs: [autorest-generate]
    uses: ./.github/workflows/nuget-publish.yml
    with:
      source-path: src/DNV.ApiClients.Veracity.DataPlatform.DataWorkbenchApiV2
      project-name: DNV.ApiClients.Veracity.DataPlatform.DataWorkbenchApiV2
      require_publish: ${{ inputs.require_publish == true || inputs.require_publish == 'true' }}
    secrets: inherit
    