name: DNV.ApiClients.Veracity.DataPlatform.DataApi

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/DataApi/**'
    - '.github/workflows/DataApi.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/DataApi/**'
    - '.github/workflows/DataApi.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      input-file: 'https://api-portal.veracity.com/docs/services/data-api/export?DocumentFormat=OpenApiJson'
      csharp: true
      output-folder: src/DNV.ApiClients.Veracity.DataPlatform.DataApi
      client-name: DataApiClient
      namespace: DNV.ApiClients.Veracity.DataPlatform.DataApi
      interface: AutoRest.ApiClients.Common.IApiClient
  nuget-publish:
    uses: ./.github/workflows/nuget-publish.yml
    with:
      source-path: src/DNV.ApiClients.Veracity.DataPlatform.DataApi
      project: DNV.ApiClients.Veracity.DataPlatform.DataApi
    secrets: inherit