name: DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/DataValidatorApi/**'
    - '.github/workflows/DataValidatorApi.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/DataValidatorApi/**'
    - '.github/workflows/DataValidatorApi.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      input-file: 'https://api-portal.veracity.com/docs/services/DataValidatorApi/export?DocumentFormat=OpenApiJson'
      csharp: true
      output-folder: src/DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi
      client-name: DataValidatorApiClient
      namespace: DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi
      interface: AutoRest.ApiClients.Common.IApiClient
  nuget-publish:
    needs: autorest-generate
    uses: ./.github/workflows/nuget-publish.yml
    with:
      source-path: src/DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi
      project: DNV.ApiClients.Veracity.DataPlatform.DataValidatorApi
    secrets: inherit
