env:
  NUGET_OUTPUT: nuget-output
  VERSION_PREFIX: 1.0.${{ github.run_number }}
  VERSION_SUFFIX: preview.${{ github.run_attempt }}

on:
  workflow_dispatch:
    inputs:
      source-path:
        required: true
        type: string
      project-name:
        required: true
        type: string
      require_publish:
        type: boolean
        default: false
  workflow_call:
    inputs:
      source-path:
        required: true
        type: string
      project-name:
        required: true
        type: string
      require_publish:
        type: boolean
        default: false
    secrets:
      NUGET_API_KEY:
        required: true
        description: "The Nuget API key"

jobs:
  nuget-publish:
    name: NuGet Publish
    if: ${{ github.event.label.name == 'Publish' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        working-directory: ${{ inputs.source-path }}
        run: |
          dotnet pack Abstractions/${{ inputs.project-name }}.ApiClient.Abstractions.csproj \
            -c Release \
            -o ${{ env.NUGET_OUTPUT }} \
            --include-symbols \
            --include-source \
            -p:VersionPrefix=${{ env.VERSION_PREFIX }}
            
          dotnet pack Implementation/${{ inputs.project-name }}.ApiClient.csproj \
            -c Release \
            -o ${{ env.NUGET_OUTPUT }} \
            --include-symbols \
            --include-source \
            -p:VersionPrefix=${{ env.VERSION_PREFIX }}

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ inputs.source-path }}/${{ env.NUGET_OUTPUT }}/*.symbols.nupkg

      - name: Publish
        if: ${{ inputs.require_publish == 'true' }}
        working-directory: ${{ inputs.source-path }}
        run: |
          dotnet nuget push --skip-duplicate '${{ env.NUGET_OUTPUT }}/*.symbols.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json