env:
  NUGET_OUTPUT: nuget-output
  VERSION_PREFIX: 1.0.${{ github.run_number }}
  VERSION_SUFFIX: preview.${{ github.run_attempt }}

on:
  workflow_dispatch:
    inputs:
      source-path:
        required: true
        type: string
      project:
        required: true
        type: string
  workflow_call:
    inputs:
      source-path:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true
        description: "The Nuget API key"

jobs:
  nuget-publish:
    name: NuGet Publish
    if: ${{ github.event.label.name == 'Publish' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        working-directory: ${{ inputs.source-path }}
        run: |
          dotnet pack ${{ inputs.project }}.Abstractions.csproj \
            -c Release \
            -o ${{ env.NUGET_OUTPUT }} \
            --include-symbols \
            --include-source \
            -p:VersionPrefix=${{ env.VERSION_PREFIX }}

          rm -rf bin obj

          dotnet pack ${{ inputs.project }}.csproj \
            -c Release \
            -o ${{ env.NUGET_OUTPUT }} \
            --include-symbols \
            --include-source \
            -p:VersionPrefix=${{ env.VERSION_PREFIX }}

      - name: Publish
        working-directory: ${{ inputs.source-path }}
        run: dotnet nuget push --skip-duplicate '${{ env.NUGET_OUTPUT }}/*.nupkg' --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json