name: DNV.ApiClients.Veracity.Identity.ServicesApiV3

on:
  workflow_dispatch:
    inputs:
      require_publish:
        type: boolean
        default: false
  push:
    branches:
    - main
    paths:
    - 'src/ServicesApiV3/**'
    - '.github/workflows/ServicesApiV3.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/ServicesApiV3/**'
    - '.github/workflows/ServicesApiV3.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      config-file: assets/ServicesApiV3.md
      project-name: DNV.ApiClients.Veracity.Identity.ServicesApiV3.ApiClient
      output-folder: src/DNV.ApiClients.Veracity.Identity.ServicesApiV3
  nuget-publish:
    needs: autorest-generate
    uses: ./.github/workflows/nuget-publish.yml
    with:
      source-path: src/DNV.ApiClients.Veracity.Identity.ServicesApiV3
      project-name: DNV.ApiClients.Veracity.Identity.ServicesApiV3
    secrets: inherit
    