name: DNV.ApiClients.Veracity.Identity.ServicesApi

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/ServicesApi/**'
    - '.github/workflows/ServicesApi.yml'
  pull_request:
    types: [ closed ]
    paths:
    - 'src/ServicesApi/**'
    - '.github/workflows/ServicesApi.yml'
jobs:
  autorest-generate:
    uses: ./.github/workflows/autorest-generate.yml
    with:
      input-file: 'https://api-portal.veracity.com/docs/services/veracity-myservices-v3/export?DocumentFormat=OpenApiJson'
      api-name: 'ServicesApi'
  # nuget-publish:
  #   uses: ./.github/workflows/nuget-publish.yml
  #   with:
  #     source-path: 'src/ServicesApi'
  #   secrets: inherit